# config/packages/api_platform.yaml
api_platform:
    title: 'Symfony Claus API'
    description: 'Santa gift stock manager.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]